### ISSUE TITLE
Pls release training dataset as well. Only query & gallery are available as of now.

### ISSUE THREAD

**Issue by sujit-dn** [serdaryildiz/ENTIRe-ID#1]
I've gone through Gdrive link & found that only query & gallery folders are available. Data in training folder is missing. Please provide training dataset as well. Thanks

**Comment by ThomaswellY** [comment]
> I've gone through Gdrive link & found that only query & gallery folders are available. Data in training folder is missing. Please provide training dataset as well. Thanks

agree with you

**Comment by serdaryildiz** [comment]
We're currently working on anonymization and agreements for research use. We aim to share the training set as soon as possible once these are finalized. We plan to complete process in the days after CVPR2025 submissions.

**Comment by edwardnguyen1705** [comment]
Hi @serdaryildiz ,
Thank you for sharing and good luck to you!
