### ISSUE TITLE
Training Set Release Schedule

### ISSUE THREAD

**Issue by igm503** [serdaryildiz/ENTIRe-ID#2]
Thanks for the new dataset! I'm very curious to see how well it works as a pretraining set for transfer to the smaller standard benchmarks like market and msmt. Do you all have an estimate for when you'll be able to release the training set?

**Comment by serdaryildiz** [comment]
Thank you for your interest! We're currently working on anonymization and agreements for research use. We aim to share the training set as soon as possible once these are finalized. Thanks for your patience!
